"""On-disk layout, in one place.

Every path the pipeline touches is derived here so that no stage invents a
directory name. Frame filenames in particular are derived, not stored twice: a
frame's rectified, cleaned and kept copies all share the raw frame's basename, so
``frames/rect/<name>`` is always computable from ``frames/raw/<name>`` and the
manifest never has to hold four paths that could disagree.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Final, Literal

# Frame set directories under out/<slug>/frames/. Only `kept` is committed;
# the rest are regenerable, which is safe only because sampling is
# deterministic (DEC-013).
FrameSet = Literal["raw", "rect", "clean", "kept"]

_ROOT_MARKERS: Final = ("configs/defaults.yaml", "pyproject.toml")


class RepoRootNotFoundError(RuntimeError):
    """The reframe checkout could not be located from the current directory."""


def find_repo_root(start: Path | None = None) -> Path:
    """Locate the reframe checkout.

    Walks up from ``start`` (default: the current directory), then falls back to
    the installed package's own location so an editable install run from
    elsewhere still finds its ``configs/`` and ``fixtures/``.
    """
    candidates: list[Path] = []
    here = (start or Path.cwd()).resolve()
    candidates.extend([here, *here.parents])
    package_root = Path(__file__).resolve().parents[2]
    candidates.append(package_root)

    for candidate in candidates:
        if all((candidate / marker).exists() for marker in _ROOT_MARKERS):
            return candidate
    raise RepoRootNotFoundError(
        "could not find the reframe repo root — expected a directory containing "
        f"{' and '.join(_ROOT_MARKERS)}"
    )


@dataclass(frozen=True)
class Paths:
    """Resolved locations for one repo, and for one video within it."""

    repo_root: Path

    # ---- repo-level -----------------------------------------------------
    @property
    def defaults_config(self) -> Path:
        return self.repo_root / "configs" / "defaults.yaml"

    @property
    def projects_dir(self) -> Path:
        return self.repo_root / "projects"

    @property
    def videos_dir(self) -> Path:
        return self.repo_root / "videos"

    @property
    def out_root(self) -> Path:
        return self.repo_root / "out"

    @property
    def fixtures_dir(self) -> Path:
        return self.repo_root / "fixtures"

    @property
    def cache_dir(self) -> Path:
        """Model response cache. Gitignored; keyed content lives inside."""
        return self.repo_root / ".cache"

    def project_profile(self, name: str) -> Path:
        return self.projects_dir / f"{name}.yaml"

    def fixture(self, slug: str) -> Path:
        return self.fixtures_dir / f"{slug}.yaml"

    def known_slugs(self) -> list[str]:
        """Every registered video, sorted. Sorted so `verify` output is stable."""
        if not self.videos_dir.is_dir():
            return []
        return sorted(
            child.name
            for child in self.videos_dir.iterdir()
            if child.is_dir() and (child / "config.yaml").exists()
        )

    def fixtured_slugs(self) -> list[str]:
        """Every video with recorded ground truth — the set `verify` re-runs."""
        if not self.fixtures_dir.is_dir():
            return []
        return sorted(path.stem for path in self.fixtures_dir.glob("*.yaml"))

    # ---- per-video ------------------------------------------------------
    def video_dir(self, slug: str) -> Path:
        return self.videos_dir / slug

    def video_config(self, slug: str) -> Path:
        """The per-video tuning surface, generated by stage 00."""
        return self.video_dir(slug) / "config.yaml"

    def source_record(self, slug: str) -> Path:
        """Absolute path plus sha256 of the source video."""
        return self.video_dir(slug) / "source.txt"

    def out_dir(self, slug: str) -> Path:
        return self.out_root / slug

    def manifest(self, slug: str) -> Path:
        return self.out_dir(slug) / "manifest.json"

    def frames_dir(self, slug: str, frame_set: FrameSet) -> Path:
        return self.out_dir(slug) / "frames" / frame_set

    def montages_dir(self, slug: str) -> Path:
        return self.out_dir(slug) / "montages"

    def markdown(self, slug: str, name: str) -> Path:
        return self.out_dir(slug) / name


def load_paths(start: Path | None = None) -> Paths:
    return Paths(repo_root=find_repo_root(start))


def frame_filename(frame_id: str, t_ms: int) -> str:
    """``f_000842`` + 842000 ms → ``f_000842__t14m02s.jpg``."""
    from reframe.timecode import format_stamp

    return f"{frame_id}__t{format_stamp(t_ms)}.jpg"


def frame_id_from_index(index: int) -> str:
    """Zero-padded, stable across re-runs — a note saying "see f_000842" must keep
    resolving, so the id is the sample index and never a hash or a counter reset."""
    return f"f_{index:06d}"


def sibling_frame(raw_path: Path, frame_set: FrameSet) -> Path:
    """Map a frame path in one set to the same frame in another set."""
    return raw_path.parent.parent / frame_set / raw_path.name
